language: ruby
rvm:
- 2.1
install: gem install jekyll
script: jekyll build
exclude: [vendor]
deploy:
  - provider: s3
    access_key_id: "AKIAIA3HHQNNXUWHU452Q"
    secret_access_key: "61v8rPfWsSfMRyGCxr/7+zNIBFFryw/0JoFGn78r"
    bucket: "humanboring.net"
    skip_cleanup: true
 - provider: s3
   access_key_id: "AKIAIA3HHQNNXUWHU452Q"
   secret_access_key: "61v8rPfWsSfMRyGCxr/7+zNIBFFryw/0JoFGn78r"
   bucket: "www.humanborint.net"
   skip_cleanup: true
