language: ruby
rvm:
- 2.1
install: 
  - gem install jekyll 
  - gem install jekyll-paginate
script: jekyll build
deploy:
  - provider: s3
    access_key_id: "AKIAJKMH7YHSIWVA4DJA"
    secret_access_key: "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"
    bucket: "humanboring.net"
    acl: public_read
    local-dir: _site
    region: eu-west-1
