title: BHP
email: me@humanboring.net
description: Ben Hamblin-Pyke’s homepage on the web
baseurl: "" 
url: “http:bhp.org.uk/” 
twitter_username: bhp_uk
github_username:  qakgob

# Build settings
markdown: kramdown
theme: poole-theme
gems:
  - jekyll-feed
  - font-awesome-sass
  - s3_website
exclude:
  - Gemfile
  - Gemfile.lock
