# Permalinks
permalink:           none

# Setup
title:               Ben Hamblin-Pyke
tagline:             Hello!
url:                 http://www.bhp.org.uk
paginate:            10
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Ben Hamblin-Pyke
  url:               https://twitter.com/bhp_uk
  email:             me@humanboring.net

# Custom vars
version:             1.0.0

# Gems
gems: 		      [jekyll-paginate]
